apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  SECRET_KEY_BASE: "{{ .Values.frab.SecretKey }}"
  SMTP_USER_NAME:
  SMTP_PASSWORD:
  DATABASE_URL: "postgres://{{ .Values.Database.User }}:{{ .Values.Database.Password }}@127.0.0.1:5432/{{ .Values.Database.Name }}"
