apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-web
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.dnsName }}
    # certmanager.k8s.io/cluster-issuer: {{ .Values.ingress.issuer }}
  labels:
    app: {{ .Release.Name }}
spec:
  backend:
    serviceName: {{ .Release.Name }}-backend
    servicePort: 30300
  tls:
  - secretName: {{ .Release.Name }}-app-tls
    hosts:
    - {{ .Values.ingress.dnsName }}
