apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  DATABASE_URL: {{ .Values.app.database_url | b64enc }}
  SESSION_SECRET: {{ .Values.app.session_secret | b64enc }}
