apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: {{ .Release.Name }}
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}
    tier: web
  ports:
  - protocol: "TCP"
    port: 30300
    targetPort: "http-port"
